### PR TITLE
Add support for Ping and Pong frames for the native implementation

### PR DESCRIPTION
**Pull request by asabil**

### CODE REVIEW

**Comment by asabil** [comment]
The web_sys interface directly mimics the web browser interface.

On the web, the User Agent is responsible for sending ping frames as needed. When building an application outside this context, we would need to manage the send of pings ourselves.

It's quite common to design protocols where the client is responsible for sending frames within a given time interval to not be considered disconnected (for example MQTT requires the client to send PINGREQ messages if it doesn't have any other data to send).

Also, when tungstenite receives ping/pong frames, those will become `FromTungsteniteMessageError` values, which I think is sub-optimal.

**Comment by jgraef** [comment]
Yes, the ping/pong frames become errors, but are then ignored by the stream.

The problem with adding `Ping`/`Pong` variants to the `Message` enum would be that the user of this crate would need to have platform-dependent code when handling `Message`s (e.g. when using `match`). We could add `Ping`/`Pong` variants regardless of platform and document that on wasm they will never be received and sending them has no effect.

**Comment by asabil** [comment]
> We could add Ping/Pong variants regardless of platform and document that on wasm they will never be received and sending them has no effect.

Yes that's definitely an option, but I think it's a rather fragile one. Instead of getting a compilation error because the feature is not supported, you suddenly start having silent protocol breakage in term of random disconnects because no data is being sent.

**Comment by martsokha** [comment]
I believe using `*Ext` for an extension trait is perfectly fine. I've seen this convention multiple times e.g. in `tracing-subscriber` (`SubscriberExt`) and `tower-http` (`ServiceBuilderExt`). In the worst case (i.e. name collisions), you can use `use *Ext as _`.

The method could be renamed to `into_websocket()` (as it's `self` into another type), but in that case, I'd also suggest renaming `UpgradedRequestBuilder` to the more specific `WebsocketRequestBuilder`.

Either solution works well, especially considering that `Request` already has special handling for `Wasm`. Instead of silently ignoring `Ping`/`Pong` in `Message`, you could add a platform-gated `#[deprecated]` attribute to provide a warning.

**Comment by jgraef** [comment]
Ping, Pong and Close frames were added.

**Pull request closed without merging**
